# Generated by Django 3.0.2 on 2025-03-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250219_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='list',
            field=models.CharField(choices=[('Ka', 'Karakter Analizi'), ('DD', 'Duygusal Durumu'), ('HO', 'Hobileri'), ('ID', 'İlişki Durumu')], default='ID', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
